kind: pipeline
type: docker
name: build

steps:
- name: test and build
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  commands:
    - dotnet restore
    - dotnet build
    - dotnet test
  environment:
    ConnectionStrings__Test:
      from_secret: connectionstringtest

---

kind: pipeline
type: ssh
name: deployment
depends_on:
  - build

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

clone:
  disable: true

steps:
  - name: move
    commands:
    - cd /home/apper/projects/StudentProgress
    - git checkout main
    - git pull
    - cd /home/apper/projects/server-utils
    - docker-compose up -d --build
    when:
      branch:
      - main
      event:
      - push
