kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: docker  
  image: plugins/docker
  settings:
    dockerfile: StudentProgress.Web/Dockerfile
    dry_run: true