kind: pipeline
type: docker
name: build

steps:
- name: build and test
  image: plugins/docker
  settings:
    dockerfile: StudentProgress.Web/Dockerfile
    repo: itsyou0o/student-progress
    dry_run: true

---

kind: pipeline
type: ssh
name: deployment

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
  - name: move
    commands:
    - cd /home/apper/projects/server-utils
    - git checkout main
    - git pull
    - docker-compose up -d --build

depends_on:
- build